// <auto-generated />
using System;
using FortesApi.Models.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FortesApi.Migrations
{
    [DbContext(typeof(FortesContext))]
    partial class FortesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FortesApi.Models.Entities.Compra", b =>
                {
                    b.Property<Guid?>("CompraKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("key")
                        .HasDefaultValue(null);

                    b.Property<DateTime?>("DataCompra")
                        .HasColumnName("data_compra")
                        .HasColumnType("datetime");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnName("descricao")
                        .HasMaxLength(100);

                    b.Property<int>("QuantidadeParcelas")
                        .HasColumnName("quantidade_parcela");

                    b.Property<decimal>("TaxaJuros")
                        .HasColumnName("taxa_juros")
                        .HasColumnType("decimal(18,4)");

                    b.Property<Guid>("UsuarioKey")
                        .HasColumnName("usuario_key");

                    b.Property<decimal>("Valor")
                        .HasColumnName("valor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnName("valor_total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("CompraKey");

                    b.HasIndex("UsuarioKey");

                    b.ToTable("TB_Compras");
                });

            modelBuilder.Entity("FortesApi.Models.Entities.Usuario", b =>
                {
                    b.Property<Guid?>("UsuarioKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("key")
                        .HasDefaultValue(null);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnName("email")
                        .HasMaxLength(250);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnName("nome")
                        .HasMaxLength(250);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnName("password")
                        .HasMaxLength(8);

                    b.HasKey("UsuarioKey");

                    b.ToTable("TB_Usuario");
                });

            modelBuilder.Entity("FortesApi.Models.Entities.Compra", b =>
                {
                    b.HasOne("FortesApi.Models.Entities.Usuario", "Usuario")
                        .WithMany("Compras")
                        .HasForeignKey("UsuarioKey")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
